
[unstable]

build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]

[build]
target = "x86_64-veil.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[net]
git-fetch-with-cli = true

